name: Continous Integration / Continous Delivery with Squirrel

on:
  push:
    branches:
     - release/squirrelbuild/*.*

env:
  PROJECT_PATH: ./WpfBuildWithSquirrel/WpfBuildWithSquirrel.csproj
  TEST_PROJECT_PATH: ./WpfBuildWithSquirrel.Test/WpfBuildWithSquirrel.Test.csproj
  OUTPUT_PROJECT_PATH: ./Output
  SQUIRREL_VERSION: 3.0.170-unstable-ge14820
  WORKING_DIR: Source/C#/WpfBuildWithSquirrel

jobs:
  CI_CD:
    runs-on: windows-latest
    defaults:
      run:
       working-directory: ${{env.WORKING_DIR}}
    steps:
       - name: Checkout
         uses: actions/checkout@v3

       - name: Install .NET Core
         uses: actions/setup-dotnet@v2
         with:
          dotnet-version: '6.0.x'
      
       - name: Build
         run: dotnet publish ${{env.PROJECT_PATH}} -c Release -r win-x64 --output ${{env.OUTPUT_PROJECT_PATH}} --self-contained=true /p:IncludeNativeLibrariesForSelfExtract=true /p:PublishSingleFile=true
      
       - name: Test
         run: dotnet test ${{env.TEST_PROJECT_PATH}}  --no-restore --verbosity normal

       - name: Install Squirrel
         run: dotnet tool install -g csq --version 3.0.170-unstable-ge14820
         
       - name: Split version code
         uses: xom9ikk/split@v1
         id: split
         with:
          string: ${{ github.ref_name }}
          separator: /
          limit: -1
      
       - name: Create Install
         run: csq pack --packId "WPFWithSquirrel" --packVersion ${{ steps.split.outputs._1 }} --packDirectory=${{env.OUTPUT_PROJECT_PATH}} --csq-sln=./WpfBuildWithSquirrel.sln --packAuthors="Actions with Squirrel"  --icon="./images/install.ico" --splashImage="./images/install.gif"

       - name: Create Release
         uses: ncipollo/release-action@v1
         with:
           artifacts: "${{env.WORKING_DIR}}/Releases/*.exe, ${{env.WORKING_DIR}}/Releases/*.nupkg,${{env.WORKING_DIR}}/Releases/RELEASES*"
           allowUpdates: true
           tag: ${{ steps.split.outputs._1 }}
           token: ${{ secrets.GITHUB_TOKEN }}

